bigbluebutton/docker

setup.sh
The external_rtp_ip and external_sip_ip were getting completely overwritten with "stun:coturn" instead of preserving the respective variable names.
=> Rewrite the RTP and SIP IPs correctly in vars.xml

scripts/setup
To ensure script continue in case of no IPv6 DNS resolution - otherwise keeps waiting forever
=> Add curl IPv6 timeout

docker-compose.tmpl.yml
After host reboot, all services but apps-akka and fsesl-akka come up again, because those didn't have a restart policy.
=> make sure the akka containers are restarted

README.md
Adding `git submodule update --init` to README.md to fix Errors with Building the Container as mentioned in Issue #101
=> Add git submodule update --init to README.md

mod/nginx/bbb/greenlight.nginx
Add a nginx redirect to allow bbb find a pre-uploaded presentation.
ref: https://docs.bigbluebutton.org/greenlight/gl-config.html#updating-from-version-prior-to-27
=> Fix for preuploaded presentations not working

scripts/generate-compose
This allows using e.g. dashes in client title.
=> Exclude CLIENT_TITLE when generating compose file

mod/freeswitch/entrypoint.sh
Certain [freeswitch sounds](https://github.com/freeswitch/freeswitch-sounds/) have uppercase letters in their path, for example `ru/RU` and `pt/BR`;
This makes it impossible to use them by setting a language in `.env`:
```
SOUNDS_LANGUAGE=ru-RU-elena
```
produces correct directory path:
```
/usr/share/freeswitch/sounds/ru/RU/elena
```
however, it cannot install this package in `entrypoint.sh`, since the package name becomes `freeswitch-sounds-ru-RU-elena` while it has to be lowercase (`freeswitch-sounds-ru-ru-elena`).
This PR fixes this by making package name always lowercase.
=> Fix freeswitch package names for languages with uppercase characters in the path

README.md, docker-compose.tmpl.yml, docs/development.md, mod/coturn/entrypoint.sh, mod/coturn/turnserver.conf, sample.env, scripts/generate-compose, scripts/setup
It might be reasonable to reintegrate coturn using the default ports (5349) even if this doesn't work for some corporate firewalls. The multiplexing approach for coturn (referenced in #73) was dropped by the jitsi devs. So it seems the current choice is an slightly imperfect coturn setup or none at all.
To allow for more individual setups using a different reverse proxy (nginx, apache), coturn should not depend on the auto HTTPS proxy.
=> Reintegrate turn with default ports and support for external certificates

docker-compose.tmpl.yml
Unfortunately, docker-compose does not respect noProxy hosts defined in ~/.docker/config.json or /etc/systemd/system/docker.service.d/http-proxy.conf and always uses proxy for healthcheck which causes problems. Resolved this by updating wget to not use proxies when checking for bbb-web health.
=> updated wget to not use proxies

scripts/setup
need to use another delimiter rather than `/` since the $CERTPATH and $KEYPATH variables contain `/` in the full path and cause the following error
```
`sed: -e expression #1, char 50: unknown option to `s'
```
fixes  #137
=> fixed sed delimiter for CERTPATH and KEYPATH

docker-compose.tmpl.yml
The template is not correctly checking if DEV_MODE is set to true.
This will always set ALLOWED_DOMAINS to an empty string and allowing to
generate certificates for any domain that points to the application.
=> https_proxy: fix setting of ALLOWED_DOMAINS

docker-compose.tmpl.yml
The coturn entrypoint checks if ENABLE_HTTPS_PROXY is set but it was not
added the the compose environment stanza so it was never set in the
container.
=> coturn: expose ENABLE_HTTPS_PROXY env variable

docker-compose.tmpl.yml, mod/periodic/Dockerfile, mod/periodic/bbb-remove-old-recordings, mod/periodic/entrypoint.sh, sample.env, scripts/generate-compose, scripts/setup
This pr adds the possbility of cleaning old recordings after N days. The task will be triggered by Periodic service.
As an admin, I'd like to activate an automatic process for removing old recordings after a configurable amount of time(days).
- During the setup user can enable the feature if they decide to enable the `recoridng` as well.
-  A boolean env vars named `REMOVE_OLD_RECORDING` for enabling the feature will be set.
-  An integer env var named `RECORDING_MAX_AGE_DAYS` for setting the max age of recording will be set.
- Official shell script developed by BigBlueButton is used for [removing recordings after N days](https://docs.bigbluebutton.org/admin/customize.html#delete-recordings-older-than-n-days)
- Official recordings utility named …
=> Automatically remove old recordings after N days

mod/bbb-web/Dockerfile
This change deletes the potrace rules from imagemagick. Otherwise it tries to use potrace, which is not installed and would create ugly monochrome slides. Without this change, https://github.com/bigbluebutton/bigbluebutton/blob/d8350f813c7611e33f1a61d65e341f7e811a2da1/bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java#L223 fails in the docker version of BBB. The users see this effect as blank slides. This path is triggered by type 3 fonts in the page. 
Background: bbb-web tries to avoid pdftocairo for pages with type 3 fonts, see https://gitlab.freedesktop.org/poppler/poppler/-/issues/268
And imagemagick changed its behaviour around version 7.0.8-65, see https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=36777
=> fix for presentation slides not displayed if they contain type 3 fonts

sample.env
Simple tweak that changes example to the actual useful values because lowercase "ru-ru" doesn't repeat directory structure of the freeswitch package.
=> Update Russian sound announcement examples

mod/etherpad/Dockerfile, mod/etherpad/settings.json
Following https://github.com/bigbluebutton/bigbluebutton/pull/14550 .
Also updated the settings.json file with https://github.com/ether/etherpad-lite/blob/1.8.17/settings.json.template .
Made sure to preserve BigBlueButton's common settings and a couple of extras
that I imagined to make sense for the docker environment:
- ip: `0.0.0.0`
BigBlueButton uses `127.0.0.1`
```
/*
* IP and port which Etherpad should bind at.
*
* Binding to a Unix socket is also supported: just use an empty string for
* the ip, and put the full path to the socket in the port parameter.
*
* EXAMPLE USING UNIX SOCKET:
*    "ip": "",                             // <-- has to be an empty string
*    "port" : "/somepath/etherpad.socket", // <-- path to a Unix socket
*/
"ip": "0.0.0.0",
"port": 9001,
```
- host: `redis` …
=> chore: update Etherpad

mod/etherpad/settings.json
At v2.5 we intoduced `bbb-pads` as a session manager for Etherpad.
Enabling `requireSession` and `editOnly` at Etherpad's settings closes
the HTTP access from all other sources besides `bbb-pads`.
=> etherpad: enforce bbb-pads session handling

mod/etherpad/settings.json
cc @frankemax
Reference: https://github.com/bigbluebutton/bigbluebutton/pull/14567
=> etherpad: avoid icons overlapping

mod/nginx/bbb/greenlight.nginx
As greenlight also allows presentation upload beforehands, right now presentations with size of >2MB would end up in a 413 - Request entity too large error. I would suggest to add here the same limit as in bbb-web for presentation upload.
=> Set client_max_body_size for greenlight

mod/nginx/bbb/learning-dashboard.nginx
This is the same as #200 but using nginx alias rather than having to create a symlink.
=> Fix learning-dashboard (alias)
